### ISSUE TITLE
Bugs with quickly removing and inserting elements.

### ISSUE THREAD

**Issue by Sloth6** [ubilabs/kd-tree-javascript#9] opened 2014-11-26 14:18 UTC
Hello and thank you for creating this library. I am creating a game that uses this library to store all enemy locations for fast nearest neighbor search. Each enemies location changes about once a second and so I remove them and insert them back into the graph to update (this may not be the best way to do it). The following coffeescript demonstrates some errors that are occurring. 

```coffeescript
enemyCount: () ->
  countR = (n) ->
    return 0 if n is null
    return 1 + countR(n.left) + countR(n.right)
  countR(@enemyKdTree.root)

#using axial coord hex grid distance function
distanceFun = (a,b) -> Hex::distanceTo.call a, b
@enemyKdTree = new kdTree [], distanceFun, ['q', 'r']
  
#create 
foo = []
for i in [0..200] by 1
  foo[i] = { q: Math.randInt(0,30), r: Math.randInt(0,30) }
  @enemyKdTree.insert foo[i]

for i in [0..200] by 1
  @enemyKdTree.remove foo[i]
  #update fields leaving obj ref the same
  foo[i].q = Math.randInt(0,30)
  foo[i].r = Math.randInt(0,30)
  @enemyKdTree.insert foo[i]

console.log enemyCount()
#This should remain 200 butgets number that are super off and different each time!
# First few runs = [285, 281, 290, 235]
```
The error rate being proportional to scale and being non deterministic makes it feel like a concurrency issue. Any thoughts?  I'll try going through the code also.

Thanks

**Comment by zadvorsky** [comment] 2015-04-14 12:21
I think I have a similar issue. This is what I intended to do:

1. process pixels in an image
2. store {x,y} positions of pixels that meet a certain requirement in the k-d tree 
3. use kd-tree to generate a path by doing a nearest-neighbor search and removing points one by one.

I ran into an issue where a point would return itself as the nearest neighbor, which broke the whole thing down.

After some debugging, I found this issue was caused by the fact that all my positions are ints (like in the post above). I worked around this issue by adding a random float offset to each pixel position (this is very hacky, but the result ended up looking better :) ).

Here is a fiddle: [http://jsfiddle.net/0Lscwhnc/](http://jsfiddle.net/0Lscwhnc/)

It's a slightly modified version of the Mutable example.

- the 'add a point' button adds 50 points for convenience
- the random points generated are rounded (floored)
- clicking on the canvas removes all points one by one, and constructs a path
- the path is logged to the console, with subsequent points being checked for sameness

the path starts out correctly, but then gets stuck on the same point.

if the flooring of x and y coordinates is removed (lines 61 and 62), the path is correct all the way to end.


Is this a bug in the code, or a limitation of k-d trees? (because the distances are too similar?)

Cheers,
Szenia

**Comment by mirceapricop** [comment] 2015-04-29 14:14
Hey, thanks for the details! Your debug info was crucial in detecting and fixing this. Though it did take a few days of hard debugging, I finally got it.

As mentioned in the pull request I sent, the tree would get corrupted sometimes when nodes had the exact same value for one of the dimensions. This is why we only saw it happening when using whole numbers (since the chances of a collision are much higher).

https://www.cs.umd.edu/class/spring2008/cmsc420/L19.kd-trees.pdf slide 12 show what we were doing wrong and what we did to fix it, as soon as the pull request is merged.

**Comment by zadvorsky** [comment] 2015-04-29 14:53
Awesome, thanks for the effort :).
I'm glad I could be of assistance.

Also, here's a few things I used your k-d tree for, in case you're curious:
http://codepen.io/zadvorsky/pen/QweGqN
http://codepen.io/zadvorsky/pen/OVJgGR
http://zadvorsky.com/#/about

**Comment by mirceapricop** [comment] 2015-04-29 15:30
Woah that's amazing stuff! Glad to see this can be used for such creative work, never even thought about the possibilities.

As a tip for your visualization, you probably already considered this, but you might want to not draw lines that are longer than a set threshold. That would make it look even more 'sketch-y', as humans usually pick up their pen when sketching over a long distance.

**Closed** 2015-04-29 16:20 UTC
